### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by The-Robby** [The-Robby/Robby-s-Prebuilts-End-Year-Project-#1]
- [x] -full overhaul comments 
- [x] -buy checks stock before buy
- [x] -builder gives notes about compatibility
- [x] -add some prebuilts to dashboard
- [x] -ability to add a prebuilt to shopping cart
- [x] -ability to save prebuilts (ask admins)
- [x] -ABILITY TO UPDATE ITEMS
- [x] -associate pictures with items
- [x] -revamp additem function to the renewed and better update function
- [x] -Update screen refresh items after updating
- [x] -add animation of shopping cart being pushed into the ditch
- [x] -maybe give update table the add function and delete additem.html
- [x] -add docstring to every function
- [x] - Requests tab, like messeges but for requests or questions
